[package]
name = "batlights"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.11.8"
clap = { version = "4.5.59", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
uuid = "1.21.0"
